### ISSUE TITLE
Install.wim not found

### ISSUE THREAD

**Issue by Abundant-Absurdity** [chris1111/Wimlib-Imagex-Package#2]
I used your software to create a windows 11 bootable usb.  The USB boots to the installer but it fails to locate install.wim.  I looked in the sources folder and install.wim was, in fact, missing.  Any idea how to fix that?

**Comment by Abundant-Absurdity** [comment]
I followed the instructions to the letter but install.wim is not added to the USB.  The video shows it happening quickly but I let my sit until the USB light stopped flashing and it still failed.  Both SIP and Gatekeeping is disabled.  I formatted the card correctly.  The only difference between what you did and what I have done is I'm not on Montery but High Sierra.  Do you think this may have caused my error?

**Comment by chris1111** [comment]
If you use a Card Reader maybe this is the problem?

Try a different USB drive

**Comment by Abundant-Absurdity** [comment]
Yep.  I've done that.  I've tried two different USB card readers and three different USB sticks.  I also tried the V1 of the program.  Nothing has worked.  I guess it must be the different OS?

**Comment by chris1111** [comment]
I don't have try on High Sierra, but I have Sierra I will try Now and report

**Comment by chris1111** [comment]
You're right, it doesn't work on Sierra either, so the program doesn't work on older versions of macOS
I'm going to put a warning to that effect.
Thanks for repport
