### ISSUE TITLE
Possible Apple Silicon support? 

### ISSUE THREAD

**Issue by jonny333** [chris1111/Wimlib-Imagex-Package#7]
I read that Wimlib has a working version for Apple silicon Macs. Does this meanthat this tool should be working on it, despite an intel cpu is part of the prerquisites?

**Comment by chris1111** [comment]
I don't see a problem? If it's to use Wimlib and create a bootable Windows USB key, it should work like on Intel macs, that remains to be seen because I don't have a Mac Apple Silicon to test it.
